accounts/urls.py
from django.urls import path
from accounts.views import signup
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup"),
]

expenses/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("receipts/", include("receipts.urls")),
    path("", RedirectView.as_view(url=reverse_lazy("home"))),
    path("accounts/", include("accounts.urls")),
]

receipts/urls.py
from django.urls import path

from receipts.views import (
    AccountCreateView,
    ExpenseCategoryListView,
    ReceiptListView,
    ReceiptCreateView,
    AccountListView,
    ExpenseCategoryCreateView,
)

urlpatterns = [
    path("", ReceiptListView.as_view(), name="home"),
    path("create/", ReceiptCreateView.as_view(), name="create_receipt"),
    path("accounts/", AccountListView.as_view(), name="list_accounts"),
    path(
        "categories/",
        ExpenseCategoryListView.as_view(),
        name="list_categories",
    ),
    path(
        "categories/create/",
        ExpenseCategoryCreateView.as_view(),
        name="create_category",
    ),
    path(
        "accounts/create/", AccountCreateView.as_view(), name="create_account"
    ),
]

accounts/models.py
from django.db import models

# Create your models here.

receipts/models.py
from django.db import models
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL


# Create your models here.
class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(
        USER_MODEL, related_name="categories", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name


class Account(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=20)
    owner = models.ForeignKey(
        USER_MODEL, related_name="accounts", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name


class Receipt(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(max_digits=10, decimal_places=3)
    tax = models.DecimalField(max_digits=10, decimal_places=3)
    date = models.DateTimeField()
    purchaser = models.ForeignKey(
        USER_MODEL, related_name="receipts", on_delete=models.CASCADE
    )
    category = models.ForeignKey(
        ExpenseCategory, related_name="receipts", on_delete=models.CASCADE
    )
    account = models.ForeignKey(
        Account, related_name="receipts", on_delete=models.CASCADE, null=True
    )

accounts/views.py
from urllib import response
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from receipts.models import Account
from django.contrib.auth.models import User
from django.contrib.auth import login

# Create your views here.
def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password1")
            user = User.objects.create_user(
                username=username,
                password=password,
            )
            user.save()
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm()
    context = {
        "form": form,
    }
    return render(request, "registration/signup.html", context)

receipts/views.py
from django.shortcuts import redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView
from receipts.models import ExpenseCategory, Account, Receipt


# Create your views here.


class ReceiptListView(LoginRequiredMixin, ListView):
    model = Receipt
    template_name = "receipts/list.html"

    def get_queryset(self):
        return Receipt.objects.filter(purchaser=self.request.user)


class AccountCreateView(LoginRequiredMixin, CreateView):
    model = Account
    template_name = "accounts/create.html"
    fields = ["name", "number"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("list_accounts")


class ExpenseCategoryCreateView(LoginRequiredMixin, CreateView):
    model = ExpenseCategory
    template_name = "expense_categories/create.html"
    fields = ["name"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        return redirect("list_categories")


class ReceiptCreateView(LoginRequiredMixin, CreateView):
    model = Receipt
    template_name = "receipts/create.html"
    fields = ["vendor", "total", "tax", "date", "category", "account"]

    def form_valid(self, form):
        item = form.save(commit=False)
        item.purchaser = self.request.user
        item.save()
        return redirect("home")


class ExpenseCategoryListView(LoginRequiredMixin, ListView):
    model = ExpenseCategory
    template_name = "expense_categories/list.html"

    def get_queryset(self):
        return ExpenseCategory.objects.filter(owner=self.request.user)


class AccountListView(LoginRequiredMixin, ListView):
    model = Account
    template_name = "accounts/list.html"

    def get_queryset(self):
        return Account.objects.filter(owner=self.request.user)

receipts/templates/accounts/create.html
{% extends 'base.html' %}

{% block form %}
<div>
    <h1>Create Account</h1>
    <form method="post">
        {% csrf_token %}
        <input type="text" name="name">
        <input type="text" name="number">
        <button>Create</button>
    </form>
</div>
{% endblock form %}

receipts/templates/accounts/list.html
{% extends 'base.html' %}

{% block content %}
<h1>Accounts</h1>
<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Number</th>
            <th>Number of Receipts</th>
        </tr>
    </thead>
    <tbody>
        {% for account in account_list %}
        <tr>
            <td>{{ account.name }}</td>
            <td>{{ account.number }}</td>
            <td>{{ account.receipts.all|length }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}

receipts/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Two Shot</title>
</head>

<body>
    <header>
        <nav>
            <ul>
                <li>
                    {% if user.is_authenticated %}
                    <a href="{% url 'logout' %}">Logout</a>
                    <a href="{% url 'home'  %}">Home</a>
                    <a href="{% url 'create_receipt'  %}">Receipt Create</a>
                    <a href="{% url 'list_categories'  %}">Category List</a>
                    <a href="{% url 'create_category'  %}">Create Category</a>
                    <a href="{% url 'list_accounts'  %}">Account List</a>
                    <a href="{% url 'create_account'  %}">Create Account</a>
                    {% else %}
                    <a href="{% url 'signup' %}">Signup</a>
                    <a href="{% url 'login' %}">Login</a>
                    {% endif %}
                </li>
            </ul>
        </nav>
    </header>
    <main>
        {% block form %}
        {% endblock form %}
        {% block content %}
        {% endblock content %}
    </main>

</body>

</html>

receipts/templates/expense_categories/create.html
{% extends 'base.html' %}

{% block form %}
<div>
    <h1>Create Category</h1>
    <form method="post">
        {% csrf_token %}
        <input type="text" name="name">
        <button>Create</button>
    </form>
</div>
{% endblock form %}

receipts/templates/expense_categories/list.html
{% extends 'base.html' %}

{% block content %}
<h1>Expense Categories</h1>
<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Number of Receipts</th>
        </tr>
    </thead>
    <tbody>
        {% for cat in expensecategory_list %}
        <tr>
            <td>{{ cat.name }}</td>
            <td>{{ cat.receipts.all|length }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}

receipts/templates/receipts/create.html
{% extends 'base.html' %}

{% block form %}
<div>
    <h1>Create Receipt</h1>
    <form method="post">
        {% csrf_token %}
        <input type="text" name="vendor">
        <input type="text" name="total">
        <input type="text" name="tax">
        <input type="text" name="date">
        <select name="category">
            <select name="account">
                <button>Create</button>
    </form>
</div>
{% endblock form %}

receipts/templates/receipts/list.html
{% extends 'base.html' %}

{% block content %}
<h1>My Receipts</h1>

<table>
    <thead>
        <tr>
            <th>Vendor</th>
            <th>Total</th>
            <th>Tax</th>
            <th>Date</th>
            <th>Category</th>
            <th>Account</th>
        </tr>
    </thead>
    <tbody>
        {% for current in receipt_list %}
        <tr>
            <td>{{ current.vendor }}</td>
            <td>{{ current.total }}</td>
            <td>{{ current.tax }}</td>
            <td>{{ current.date|date:'m/d/Y' }}</td>
            <td>{{ current.category }}</td>
            <td>{{ current.account }}</td>
        </tr>
        {% endfor current %}
    </tbody>
</table>
{% endblock content %}